//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BargainFetcherCrawler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BargainFetcherCrawler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mosógép, https://www.emag.hu/mosogepek/
        ///Szárítógép, https://www.emag.hu/szaritogepek/
        ///Hűtőszekrény, https://www.emag.hu/hutoszekrenyek/
        ///Kombinált hűtő, https://www.emag.hu/kombinalt-hutok/
        ///Side-by-side hűtő, https://www.emag.hu/side-by-side-hutok/
        ///Fagyasztőszekrény, https://www.emag.hu/fagyasztoszekrenyek/
        ///Fagyasztóláda, https://www.emag.hu/fagyasztoladak/
        ///Hűtővitrin, https://www.emag.hu/hutovitrinek/
        ///Mosogatógép, https://www.emag.hu/mosogatogepek/
        ///Páraelszívó, https://www.emag.hu/paraelszivok/
        ///Fő [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LinksCategoriesEMAG {
            get {
                return ResourceManager.GetString("LinksCategoriesEMAG", resourceCulture);
            }
        }
    }
}
